### ISSUE TITLE
"failed to take screenshot" error with automationName: flutter

### ISSUE THREAD

**Issue by dwwhalen** [percy/percy-appium-js#88]
I am attempting to get Percy snapshots working with a basic Flutter app.  In the log I see:
`[percy] [Initial page] failed to take screenshot`

This test is using `"appium:automationName": "flutter"`.  When I switch it to `"appium:automationName": "UiAutomator2"` then it's all good.  But I really need it to work with flutter.

My repo is here https://github.com/dwwhalen/flutter_webdriver_appium.  

You can reproduce the issue with `npm run test-hello-android-percy`

**Comment by pankaj443** [comment]
Hey @dwwhalen, Currently there is no first-class support for Flutter but can be easily used with Appium Flutter Driver.
You can add a helper method:
```
async function percyScreenshotFlutter(driver, name, options) {
  await driver.switchContext('NATIVE_APP');
  // call percyScreenshot when current context is NATIVE_APP
  await percyScreenshot(driver, name, options);
  // switch back to flutter context
  await driver.switchContext('FLUTTER');
}
```
Update your code to call this helper method:
`await percyScreenshotFlutter(driver, 'Home page')`

**Comment by dwwhalen** [comment]
Thank you @pankaj443.  This works and does what I need it to.  I appreciate your quick response!
